# Generated by Django 3.0 on 2019-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(default='', max_length=15)),
                ('start', models.PositiveSmallIntegerField(default=1)),
                ('end', models.PositiveSmallIntegerField(default=255)),
            ],
        ),
    ]
